### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by ericp1337** [mgarc138/AGILESE359-459#3]
We should start writing some tests for the new code that was written since we only have a few tests currently.

**Comment by mgarc138** [comment]
Yes we need that for this week . More like a story level test !

On Monday, November 2, 2015, Eric Pfeiffer notifications@github.com wrote:

> We should start writing some tests for the new code that was written since
> we only have a few tests currently.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mgarc138/AGILESE359-459/issues/3.

## 

Marlon Garcia

**Comment by ericp1337** [comment]
Closing since project is done as of Monday.
