### ISSUE TITLE
Grid Navigation

### ISSUE THREAD

**Issue by ericp1337** [mgarc138/AGILESE359-459#7]
Need to implement grid navigation so that the clean sweep can go through the different rooms and clean them, then move on to the next room until all done.
I am currently trying to find an algorithm that would be good for this sort of thing, so if anyone knows of any, please let me know so I can look at it and try to implement it.

**Comment by mgarc138** [comment]
We can use a Minimum Spanning Tree and Prim's Algorithm to navigate all the cells but I think right now we may not have time to implement that It takes a lot of time. I have a sudo code of the that algorithm I don't know if you want it.
